const ROOM_GRACE_MS = 40000;
const DRAW_MS = 40000;
const GUESS_MS = 40000;
const PROMPT_PICK_MS = 15000;

const GUESS_POINTS_MAX = 12;
const GUESS_POINTS_MIN = 3;
const GUESS_ORDER_PENALTY = 2;
const DRAWER_POINTS_PER_CORRECT = 2;
const MAX_GUESS_ATTEMPTS = 5;
const PROMPT_OPTIONS_COUNT = 4;

module.exports = {
  ROOM_GRACE_MS,
  DRAW_MS,
  GUESS_MS,
  PROMPT_PICK_MS,
  GUESS_POINTS_MAX,
  GUESS_POINTS_MIN,
  GUESS_ORDER_PENALTY,
  DRAWER_POINTS_PER_CORRECT,
  MAX_GUESS_ATTEMPTS,
  PROMPT_OPTIONS_COUNT
};
